// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stnonqjvholbwbaetlul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0bm9ucWp2aG9sYndiYWV0bHVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjM3NjUsImV4cCI6MjA3MTA5OTc2NX0.oqzlqOHcVPk3_JT8aJpgU_kAWy2praBTEA1lRlgFn-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});